from typing import Any

# Словари с параметрами для парсинга

WEBDRIVER_OPTIONS: dict[str, list[Any]] = {
    "options_list": [
        "--disk-cache-dir=./selenium:/browser_cache",
        "--start-minimized",
        "--allow-running-insecure-content",
        "--autoplay-policy=user-gesture-required",
        "--disable-add-to-shelf",
        "--disable-background-networking",
        "--disable-background-timer-throttling",
        "--disable-backgrounding-occluded-windows",
        "--disable-blink-features=AutomationControlled",
        "--disable-breakpad",
        "--disable-checker-imaging",
        "--disable-client-side-phishing-detection",
        "--disable-datasaver-prompt",
        "--disable-desktop-notifications",
        "--disable-dev-shm-usage",
        "--disable-domain-reliability",
        "--disable-extensions",
        "--disable-hang-monitor",
        "--disable-infobars",
        "--disable-ipc-flooding-protection",
        "--disable-logging",
        "--disable-notifications",
        "--disable-popup-blocking",
        "--disable-prompt-on-repost",
        "--disable-renderer-backgrounding",
        "--disable-setuid-sandbox",
        "--disable-site-isolation-trials",
        "--disable-sync",
        "--disable-web-security",
        "--enable-automation",
        "--force-color-profile=srgb",
        "--force-device-scale-factor=1",
        "--ignore-certificate-errors",
        "--metrics-recording-only",
        "--mute-audio",
        "--no-default-browser-check",
        "--no-first-run",
        "--no-sandbox",
        "--password-store=basic",
        "--test-type",
        "--use-mock-keychain",
        "--disable-component-extensions-with-background-pages",
        "--disable-features=TranslateUI,BlinkGenPropertyTrees",
    ]
}

WEBDRIVER_EX_OPTIONS: dict[str, Any] = {
    "excludeSwitches": ["enable-automation"],
    "useAutomationExtension": False,
    "detach": True,
    "prefs": {"profile.managed_default_content_settings.images": 2},
}


AUTO_CLASSES: dict[str, str] = {
    "bad_link": "styles-module-content-qVSTx",
    "no_results": "no-results-root-bWQVm",
    "find_button": "button-textBox-_SF60",
    "location": "main-textWrapper-svdf1",
    "popup_clear_button": "suggest-icon-qI_yN",
    "popup_input_line": "popup-city-gR9j3",
    "popup_selected_region": "suggest-suggest-content-raQZy",
    "popup_find_button": "popup-buttons-WICnh",
    "price": "input-input-Zpzc1",
    "year": "suggest-input-rORJM",
    "expand": "collapsible-container-expand-fj_ig",
    "suggest_list": "suggest-suggests-CzXfs",
    "checkbox": "checkbox-input-uPrBY",
    "transmission": "styles-outline-V_K3G",
    "transmission_list": "styles-checkbox-cqD_S",
    "ads_number": "page-title-count-wQ7pG",
    "ads": "items-items-kAJAg",
    "ad": "iva-item-body-KLUuy",
    "description": "iva-item-descriptionStep-C0ty1",
    "geo": "geo-root-zPwRk",
    "date": "iva-item-dateInfoStep-_acjp",
}

AUTO_FEATURES_DICT: dict[str, list[str]] = {
    "gear_engine_list": [
        "rear-wheel",
        "front-wheel",
        "four-wheel",
        "petrol",
        "gas",
        "hybrid",
        "diesel",
        "electric",
    ],
    "transmission_list": ["", "automatic", "variable", "robotic", "manual"],
    "ad_attributes": [
        "link",
        "price",
        "auto",
        "engine",
        "transmission",
        "year",
        "mileage",
        "geo",
        "date",
        "description",
    ],
}

BUTTON_TEXT: list[str] = [
    "Показать объявления",
    "Ничего не найдено"
]


AUTO_MARKS: list[str] = [
    "acura",
    "alfa romeo",
    "alpina",
    "asia",
    "aston martin",
    "audi",
    "aurus",
    "bentley",
    "bmw",
    "brilliance",
    "bugatti",
    "buick",
    "byd",
    "cadillac",
    "changan",
    "chery",
    "chevrolet",
    "chrysler",
    "citroen",
    "dacia",
    "daewoo",
    "daihatsu",
    "datsun",
    "delorean",
    "derways",
    "dodge",
    "dongfeng",
    "faw",
    "ferrari",
    "fiat",
    "ford",
    "foton",
    "freightliner",
    "geely",
    "genesis",
    "gmc",
    "great wall",
    "hafei",
    "haima",
    "haval",
    "hawtai",
    "hino",
    "honda",
    "hummer",
    "hyundai",
    "infiniti",
    "iran khodro",
    "isuzu",
    "jac",
    "jaguar",
    "jeep",
    "kia",
    "koenigsegg",
    "lamborghini",
    "lancia",
    "land rover",
    "lexus",
    "lincoln",
    "lotus",
    "luxgen",
    "marussia",
    "maserati",
    "maybach",
    "mazda",
    "mclaren",
    "mercedes-benz",
    "mercury",
    "mini",
    "mitsubishi",
    "mitsuoka",
    "nissan",
    "oldsmobile",
    "opel",
    "pagani",
    "peugeot",
    "plymouth",
    "pontiac",
    "porsche",
    "proton",
    "ravon",
    "renault",
    "renault samsung",
    "rolls-royce",
    "rover",
    "saab",
    "saturn",
    "scion",
    "seat",
    "skoda",
    "smart",
    "ssangyong",
    "subaru",
    "suzuki",
    "tesla",
    "tianye",
    "toyota",
    "volkswagen",
    "volvo",
    "vortex",
    "zotye",
    "zx",
    "газ",
    "заз",
    "иж",
    "ваз",
    "луаз",
    "москвич",
    "тагаз",
    "уаз",
]


AUTO_MODELS: dict[str, str] = {
    "acura": [
        "cdx",
        "cl",
        "csx",
        "el",
        "ilx",
        "integra",
        "legend",
        "mdx",
        "nsx",
        "rdx",
        "rl",
        "rlx",
        "rsx",
        "slx",
        "tl",
        "tlx",
        "tsx",
        "vigor",
        "zdx",
    ],
    "alfa romeo": [
        "145",
        "146",
        "147",
        "155",
        "156",
        "159",
        "164",
        "166",
        "33",
        "33 stradale",
        "4c",
        "75",
        "8c",
        "brera",
        "giulia",
        "giulietta",
        "gt",
        "gtv",
        "mito",
        "spider",
        "stelvio",
        "tonale",
    ],
    "alpina": [
        "b10",
        "b11",
        "b12",
        "b3",
        "b4",
        "b5",
        "b6",
        "b7",
        "b8",
        "b9",
        "c1",
        "c2",
        "d10",
        "d3",
        "d4",
        "d5",
        "roadster",
        "xb7",
        "xd3",
        "xd4",
    ],
    "asia": ["rocsta"],
    "aston martin": [
        "ar1",
        "cygnet",
        "db11",
        "db5",
        "db7",
        "db9",
        "dbs",
        "dbx",
        "lagonda",
        "one-77",
        "rapide",
        "tickford capri",
        "v8",
        "vanquish",
        "vanquish volante",
        "vantage",
        "virage",
        "zagato",
    ],
    "audi": [
        "100",
        "200",
        "50",
        "80",
        "90",
        "a1",
        "a2",
        "a3",
        "a4",
        "a4 allroad quattro",
        "a5",
        "a6",
        "a6 allroad quattro",
        "a7",
        "a8",
        "cabriolet",
        "coupe",
        "e-tron",
        "e-tron gt",
        "e-tron s",
        "e-tron sportback",
        "e-tron sportback s",
        "q2",
        "q2 e-tron",
        "q3",
        "q3 sportback",
        "q4 e-tron",
        "q4 sportback e-tron",
        "q5",
        "q5 e-tron",
        "q5 sportback",
        "q6",
        "q7",
        "q8",
        "quattro",
        "r8",
        "rs e-tron gt",
        "rs q3",
        "rs q3 sportback",
        "rs q8",
        "rs2",
        "rs3",
        "rs4",
        "rs5",
        "rs6",
        "rs7",
        "s2",
        "s3",
        "s4",
        "s5",
        "s6",
        "s7",
        "s8",
        "sq5",
        "sq5 sportback",
        "sq7",
        "sq8",
        "tt",
        "tt rs",
        "tts",
        "v8",
    ],
    "aurus": ["komendant", "senat"],
    "bentley": [
        "arnage",
        "azure",
        "bentayga",
        "brooklands",
        "continental",
        "continental gt",
        "eight",
        "flying spur",
        "mulsanne",
        "r-type",
        "s",
        "t серия",
        "turbo r",
    ],
    "bmw": [
        "02 (e10)",
        "1 серия",
        "1m",
        "2 серия",
        "2 серия active tourer",
        "2 серия gran tourer",
        "3 серия",
        "3 серия gran turismo",
        "321",
        "326",
        "340",
        "4 серия",
        "5 серия",
        "5 серия gran turismo",
        "503",
        "6 серия",
        "6 серия gran turismo",
        "7 серия",
        "8 серия",
        "e3",
        "e9",
        "i3",
        "i4",
        "i5",
        "i7",
        "i8",
        "ix",
        "ix1",
        "ix2",
        "ix3",
        "m2",
        "m3",
        "m4",
        "m5",
        "m6",
        "m8",
        "x1",
        "x2",
        "x3",
        "x4",
        "x5",
        "x6",
        "x7",
        "xm",
        "z1",
        "z3",
        "z4",
        "z8",
    ],
    "brilliance": ["h230", "h530", "m1", "m2", "m3", "v3", "v5"],
    "bugatti": ["chiron", "veyron"],
    "buick": [
        "cascada",
        "century",
        "electra e5",
        "enclave",
        "encore",
        "encore gx",
        "envision",
        "envision plus",
        "envista",
        "excelle",
        "excelle gt",
        "excelle gx",
        "excelle xt",
        "gl6",
        "gl8",
        "gl8 avenir",
        "gl8 century",
        "gl8 es",
        "gl8 firstland",
        "lacrosse",
        "lesabre",
        "lucerne",
        "park avenue",
        "rainier",
        "regal",
        "rendezvous",
        "riviera",
        "roadmaster",
        "sail",
        "skylark",
        "special",
        "terraza",
        "velite 5",
        "velite 6",
        "velite 7",
        "verano",
        "verano gs",
        "verano pro",
    ],
    "byd": [
        "destroyer 05",
        "dolphin",
        "e1",
        "e2",
        "e3",
        "e5",
        "e6",
        "f0",
        "f3",
        "f5",
        "f6",
        "f7",
        "f8",
        "flyer",
        "frigate 07",
        "g3",
        "g6",
        "han",
        "m6",
        "qin",
        "qin plus",
        "qin pro",
        "s6",
        "s7",
        "seagull",
        "seal",
        "song",
        "song max",
        "song plus",
        "song pro",
        "tang",
        "yuan",
        "yuan plus",
        "yuan pro",
    ],
    "cadillac": [
        "ats",
        "bls",
        "brougham",
        "catera",
        "ct4",
        "ct5",
        "ct6",
        "cts",
        "deville",
        "dts",
        "eldorado",
        "elr",
        "escalade",
        "fleetwood",
        "gt4",
        "lyriq",
        "seville",
        "srx",
        "sts",
        "xlr",
        "xt4",
        "xt5",
        "xt6",
        "xts",
    ],
    "changan": [
        "alsvin",
        "benben",
        "cs15",
        "cs35",
        "cs35 plus",
        "cs55",
        "cs55 plus",
        "cs75",
        "cs75 plus",
        "cs85 coupe",
        "cs95",
        "cs95 plus",
        "deepal shenlan s7",
        "deepal shenlan sl03",
        "eado",
        "eado dt",
        "eado plus",
        "eado xt",
        "hunter",
        "hunter plus",
        "lamore",
        "lantop",
        "linmax",
        "qiyuan a05",
        "qiyuan a07",
        "qiyuan q05",
        "raeton",
        "raeton cc",
        "raeton plus",
        "sc 1030",
        "uni-k",
        "uni-t",
        "uni-v",
        "yida",
    ],
    "chery": [
        "a11",
        "a5",
        "amulet a15",
        "arrizo 3",
        "arrizo 5",
        "arrizo 5 gt",
        "arrizo 5 plus",
        "arrizo 5 pro",
        "arrizo 5e",
        "arrizo 6",
        "arrizo 6 pro",
        "arrizo 7",
        "arrizo 8",
        "arrizo ex",
        "arrizo gx",
        "arrizo m7",
        "big ant eq5",
        "bonus 3 - a19",
        "bonus a13",
        "crosseastar b14",
        "e5",
        "eastar b11",
        "eq1",
        "eq7",
        "explore 06",
        "fora a21",
        "indis s18d",
        "karry",
        "kimo a1",
        "m11",
        "oriental son b11",
        "qq ice cream",
        "qq sweet",
        "qq6 s21",
        "tiggo 2",
        "tiggo 2 pro",
        "tiggo 3",
        "tiggo 3x",
        "tiggo 3xe",
        "tiggo 4",
        "tiggo 4 pro",
        "tiggo 5",
        "tiggo 5x",
        "tiggo 7",
        "tiggo 7 plus",
        "tiggo 7 pro",
        "tiggo 7 pro max",
        "tiggo 7 pro plug-in-hybrid",
        "tiggo 8",
        "tiggo 8 plus",
        "tiggo 8 pro",
        "tiggo 8 pro e+ hybrid",
        "tiggo 8 pro max",
        "tiggo 9",
        "tiggo e",
        "tiggo t11",
        "v5",
        "very a13",
    ],
    "chevrolet": [
        "3600",
        "alero",
        "astro",
        "avalanche",
        "aveo",
        "bel air",
        "beretta",
        "blazer",
        "blazer k5",
        "blazer s-10",
        "bolt",
        "camaro",
        "caprice",
        "captiva",
        "cavalier",
        "celebrity",
        "cobalt",
        "colorado",
        "corsica",
        "corvette",
        "cruze",
        "damas",
        "el camino",
        "epica",
        "equinox",
        "evanda",
        "express",
        "groove",
        "hhr",
        "impala",
        "lacetti",
        "lanos",
        "lumina",
        "lumina apv",
        "malibu",
        "menlo",
        "metro",
        "monte carlo",
        "monza",
        "mw",
        "nexia",
        "niva",
        "nubira",
        "onix",
        "optra",
        "orlando",
        "prisma",
        "rezzo",
        "s10",
        "silverado",
        "sonic",
        "spark",
        "spin",
        "ssr",
        "starcraft",
        "suburban",
        "tacuma",
        "tahoe",
        "tracker",
        "trailblazer",
        "traverse",
        "trax",
        "uplander",
        "van",
        "venture",
        "viva",
        "volt",
        "yukon",
    ],
    "chrysler": [
        "180",
        "200",
        "300",
        "300 letter series",
        "300c",
        "300m",
        "aspen",
        "cirrus",
        "concorde",
        "cordoba",
        "crossfire",
        "daytona",
        "fifth avenue",
        "grand voyager",
        "imperial",
        "intrepid",
        "le baron",
        "lhs",
        "neon",
        "new yorker",
        "newport",
        "pacifica",
        "prowler",
        "pt cruiser",
        "saratoga",
        "sebring",
        "stratus",
        "town and country",
        "vision",
        "voyager",
        "ypsilon",
    ],
    "citroen": [
        "2cv",
        "ax",
        "berlingo",
        "bx",
        "c-crosser",
        "c-elysee",
        "c-zero",
        "c1",
        "c15",
        "c2",
        "c25",
        "c3",
        "c3 aircross",
        "c3 picasso",
        "c4",
        "c4 aircross",
        "c4 cactus",
        "c4 picasso",
        "c4 spacetourer",
        "c5",
        "c5 aircross",
        "c6",
        "c8",
        "ds",
        "ds3",
        "ds3 crossback",
        "ds4",
        "ds5",
        "ds7",
        "e-mehari",
        "evasion",
        "grand c4 picasso",
        "grand c4 spacetourer",
        "gs",
        "jumper",
        "jumpy",
        "nemo",
        "saxo",
        "spacetourer",
        "visa",
        "xantia",
        "xm",
        "xsara",
        "xsara picasso",
        "zx",
    ],
    "dacia": [
        "dokker",
        "duster",
        "lodgy",
        "lodgy stepway",
        "logan",
        "logan mcv",
        "logan mcv stepway",
        "logan pick-up",
        "logan van",
        "sandero",
        "sandero stepway",
        "solenza",
        "supernova",
    ],
    "daewoo": [
        "alpheon",
        "aranos",
        "assol",
        "bh120",
        "bs106",
        "cielo",
        "condor",
        "damas",
        "espero",
        "evanda",
        "g2x",
        "gentra",
        "kalos",
        "korando",
        "labo",
        "lacetti",
        "lanos",
        "leganza",
        "lemans",
        "lublin 3",
        "magnus",
        "matiz",
        "nexia",
        "novus",
        "nubira",
        "prince",
        "racer",
        "rezzo",
        "royale",
        "sens",
        "tacuma",
        "tico",
        "tosca",
        "winstorm",
    ],
    "daihatsu": [
        "altis",
        "applause",
        "atrai",
        "atrai7",
        "be-go",
        "boon",
        "boon luminas",
        "cargo",
        "cast",
        "charade",
        "charade de tomaso",
        "charade social",
        "charmant",
        "coo",
        "copen",
        "cuore",
        "delta",
        "domino",
        "esse",
        "extol",
        "feroza",
        "gran max",
        "gran move",
        "hijet",
        "hijet caddie",
        "hijet truck",
        "leeza",
        "materia",
        "max",
        "mebius",
        "midget ii",
        "mira",
        "mira avy",
        "mira cocoa",
        "mira e:s",
        "mira gino",
        "mira gino 1000",
        "mira moderno",
        "mira tocot",
        "move",
        "move canbus",
        "move conte",
        "move latte",
        "naked",
        "opti",
        "pyzar",
        "rocky",
        "rugger",
        "sirion",
        "social",
        "sonica",
        "storia",
        "taft",
        "tanto",
        "tanto exe",
        "terios",
        "terios kid",
        "terios lucia",
        "thor",
        "trevis",
        "wake",
        "xenia",
        "yrv",
    ],
    "datsun": ["mi-do", "on-do"],
    "delorean": ["dmc-12"],
    "derways": ["aurora", "cowboy", "land crown", "lifan", "plutus", "shuttle"],
    "dodge": [
        "aries",
        "avenger",
        "caliber",
        "caravan",
        "challenger",
        "charger",
        "cirrus",
        "dakota",
        "dart",
        "durango",
        "dynasty",
        "grand caravan",
        "hornet",
        "intrepid",
        "jcuv",
        "journey",
        "magnum",
        "neon",
        "nitro",
        "raider",
        "ram",
        "ram van",
        "ramcharger",
        "shadow",
        "spirit",
        "sprinter",
        "stealth",
        "stratus",
        "viper",
    ],
    "dongfeng": [
        "580",
        "a9",
        "aeolus a30",
        "aeolus a60",
        "aeolus ax3",
        "aeolus ax4",
        "aeolus ax5",
        "aeolus ax7",
        "aeolus ax7 plus",
        "aeolus ax7 pro",
        "aeolus e70",
        "aeolus haohan",
        "aeolus haoji",
        "aeolus yixuan",
        "aeolus yixuan gs",
        "aeolus yixuan max",
        "ax4",
        "ax7",
        "captain-t",
        "df6",
        "dfa серия",
        "dfl серия",
        "fengon 500",
        "fengon 580",
        "fengon 580 pro",
        "fengon e3",
        "fengon ix5",
        "fengon ix7",
        "fengon mini ev",
        "fengon s560",
        "h30 cross",
        "k33-561",
        "mengshi m-hero 917",
        "mpv",
        "oting",
        "paladin",
        "rich",
        "rich 6",
        "rich 7",
        "s30",
        "shine max",
        "sokon v21",
    ],
    "faw": [
        "1010",
        "1041",
        "1051",
        "27731",
        "6350",
        "6371",
        "bestune b70",
        "bestune b70s",
        "bestune e01",
        "bestune nat",
        "bestune t33",
        "bestune t55",
        "bestune t55s",
        "bestune t77",
        "bestune t99",
        "besturn b30",
        "besturn b50",
        "besturn b70",
        "besturn x40",
        "besturn x40 ev",
        "besturn x80",
        "cargovan",
        "j5 ca3252/3253",
        "j5 ca3312",
        "j6 ca3250",
        "j6 ca3310",
        "j6 ca4250",
        "jinn",
        "junpai d60",
        "landmark",
        "oley",
        "senia r7",
        "senia r9",
        "v2",
        "v5",
        "vita",
    ],
    "ferrari": [
        "296 gtb",
        "296 gts",
        "328",
        "348",
        "360",
        "456",
        "458 italia",
        "458 spider",
        "458 speciale",
        "488 gtb",
        "488 spider",
        "488 pista",
        "550 barchetta",
        "575m maranello",
        "599 gtb fiorano",
        "599 gto",
        "612 scaglietti",
        "812 gts",
        "812 superfast",
        "california",
        "daytona sp3",
        "enzo ferrari",
        "f12 berlinetta",
        "f12 tdf",
        "f355",
        "f40",
        "f430",
        "f50",
        "f8 spider",
        "f8 tributo",
        "ff",
        "fxx",
        "gtc4lusso",
        "laferrari",
        "monza sp",
        "portofino",
        "purosangue",
        "roma",
        "sf90 stradale",
        "superamerica",
        "testarossa",
    ],
    "fiat": [
        "1 серия",
        "124 spider",
        "125",
        "127",
        "500",
        "500l",
        "500x",
        "albea",
        "barchetta",
        "brava",
        "bravo",
        "cinquecento",
        "coupe",
        "croma",
        "doblo",
        "ducato",
        "fiorino",
        "freemont",
        "fullback",
        "grande punto",
        "idea",
        "linea",
        "marea",
        "multipla",
        "palio",
        "panda",
        "punto",
        "qubo",
        "regata",
        "ritmo",
        "scudo",
        "sedici",
        "seicento",
        "siena",
        "stilo",
        "strada",
        "talento",
        "tempra",
        "tipo",
        "ulysse",
        "uno",
    ],
    "ford": [
        "aerostar",
        "b-max",
        "bronco",
        "bronco ii",
        "bronco sport",
        "c-max",
        "capri",
        "cargo",
        "contour",
        "cougar",
        "crown victoria",
        "e серия",
        "econoline",
        "econovan",
        "ecosport",
        "edge",
        "eifel",
        "escape",
        "escort",
        "everest",
        "evos",
        "excursion",
        "expedition",
        "explorer",
        "f-max",
        "f150",
        "f250",
        "f350",
        "f450",
        "fairlane",
        "festiva",
        "fiesta",
        "five hundred",
        "flex",
        "focus",
        "focus rs",
        "focus st",
        "freda",
        "freestar",
        "freestyle",
        "fusion",
        "galaxie",
        "galaxy",
        "granada",
        "grand c-max",
        "gt",
        "ikon",
        "ixion",
        "ka",
        "kuga",
        "laser",
        "maverick",
        "mondeo",
        "mustang",
        "mustang mach-e",
        "orion",
        "p100",
        "probe",
        "puma",
        "ranger",
        "s-max",
        "scorpio",
        "sierra",
        "spectron",
        "sportka",
        "streetka",
        "taunus",
        "taurus",
        "telstar",
        "tempo",
        "territory",
        "th!nk",
        "thunderbird",
        "tourneo",
        "tourneo connect",
        "tourneo courier",
        "tourneo custom",
        "transit",
        "transit connect",
        "transit courier",
        "transit custom",
        "v8",
        "windstar",
    ],
    "foton": [
        "alpha",
        "auman bj10",
        "auman bj11",
        "auman bj32",
        "auman bj33",
        "auman bj425",
        "auman bj51",
        "auman est a",
        "aumark bj10",
        "aumark bj11",
        "conqueror 3",
        "conqueror 5",
        "conqueror 7",
        "conqueror plus",
        "ollin bj10",
        "sauvana",
        "toano",
        "tunland",
        "tunland f9",
        "tunland g7",
        "tunland g9",
        "view",
    ],
    "freightliner": [
        "business class fl",
        "business class m2",
        "century",
        "columbia",
        "flc",
        "fld",
        "freightliner",
        "sprinter",
    ],
    "geely": [
        "atlas",
        "atlas pro",
        "belgee x50",
        "binrui",
        "binrui cool",
        "binyue",
        "borui",
        "borui ge",
        "boyue",
        "boyue cool",
        "boyue l",
        "boyue pro",
        "boyue x",
        "ck",
        "coolray",
        "emgrand",
        "emgrand ec7",
        "emgrand ec8",
        "emgrand gl",
        "emgrand gt",
        "emgrand l",
        "emgrand s",
        "emgrand x7",
        "farizon fx",
        "fc",
        "galaxy l7",
        "gc6",
        "ge",
        "geometry a ge11",
        "geometry a pro",
        "geometry c ge13",
        "geometry e",
        "gs",
        "haoyue",
        "haoyue l",
        "icon",
        "jiaji",
        "lc cross",
        "mk",
        "mk cross",
        "monjaro",
        "okavango",
        "otaka ck",
        "preface",
        "sl",
        "tugella fy11",
        "vision",
        "vision s1",
        "vision x1",
        "vision x3",
        "vision x3 pro",
        "vision x6",
        "vision x6 pro",
        "xingyue",
        "xingyue l",
        "xingyue s",
    ],
    "genesis": ["eq900", "g70", "g80", "g90", "gv60", "gv70", "gv80", "gv80 coupe"],
    "gmc": [
        "acadia",
        "canyon",
        "envoy",
        "hummer ev",
        "jimmy",
        "safari",
        "savana",
        "sierra",
        "sonoma",
        "suburban",
        "terrain",
        "typhoon",
        "vandura",
        "yukon",
    ],
    "great wall": [
        "coolbear",
        "cowry",
        "deer",
        "florid",
        "hover",
        "hover h3",
        "hover h5",
        "hover h6",
        "hover m2",
        "hover m4",
        "pao",
        "pegasus",
        "peri",
        "poer",
        "poer kingkong",
        "safe",
        "sailor",
        "shanhai poer",
        "sing",
        "voleex c30",
        "wingle",
        "wingle 7",
    ],
    "hafei": ["brio", "princip", "sigma", "simbo"],
    "haima": [
        "2",
        "3",
        "6p",
        "7",
        "7x",
        "7x-e",
        "8s",
        "aishang ev",
        "family",
        "family f5",
        "freema",
        "m3",
    ],
    "haval": [
        "big dog dagou",
        "chitu",
        "cool dog kagou",
        "dargo",
        "f5",
        "f7",
        "f7x",
        "h-dog",
        "h1",
        "h2",
        "h2s",
        "h4",
        "h4 pro",
        "h5",
        "h6",
        "h6 coupe",
        "h6s",
        "h7",
        "h8",
        "h9",
        "jolion",
        "m6",
        "m6 plus",
        "raptor",
        "shenshou",
        "xialong",
        "xialong max",
    ],
    "hawtai": [
        "a25",
        "b21",
        "boliger",
        "iev230",
        "laville",
        "shengdafei",
        "shengdafei 5",
        "xev260",
    ],
    "hino": [
        "300",
        "500",
        "700",
        "dutro",
        "fc",
        "fd",
        "fh",
        "fn",
        "fq",
        "fr",
        "fs",
        "fw",
        "hino",
        "profia",
        "ranger",
        "sh",
        "super dolphin",
    ],
    "honda": [
        "1300",
        "accord",
        "accord inspire",
        "acty",
        "acty truck",
        "airwave",
        "ascot",
        "ascot innova",
        "avancier",
        "ballade",
        "beat",
        "breeze",
        "capa",
        "city",
        "civic",
        "civic ferio",
        "civic shuttle",
        "civic type r",
        "clarity",
        "concerto",
        "cr-v",
        "cr-x",
        "cr-x del sol",
        "cr-z",
        "crider",
        "crossroad",
        "crosstour",
        "domani",
        "e",
        "e:np1",
        "e:ns1",
        "edix",
        "element",
        "elysion",
        "fit",
        "fit aria",
        "fit shuttle",
        "fr-v",
        "freed",
        "freed spike",
        "freed+",
        "grace",
        "horizon",
        "hr-v",
        "insight",
        "inspire",
        "integra",
        "integra sj",
        "jade",
        "jazz",
        "lagreat",
        "legend",
        "life",
        "life dunk",
        "logo",
        "m-nv",
        "mdx",
        "mobilio",
        "mobilio spike",
        "n-box",
        "n-box slash",
        "n-box+",
        "n-one",
        "n-van",
        "n-wgn",
        "nsx",
        "odyssey",
        "orthia",
        "partner",
        "passport",
        "pilot",
        "prelude",
        "quint",
        "quintet",
        "rafaga",
        "ridgeline",
        "s-mx",
        "s2000",
        "s660",
        "saber",
        "shuttle",
        "stepwgn",
        "stream",
        "street",
        "that's",
        "today",
        "torneo",
        "ur-v",
        "vamos",
        "vamos hobio",
        "ve-1",
        "vezel",
        "vigor",
        "wr-v",
        "x-nv",
        "xr-v",
        "z",
        "zest",
        "zr-v",
    ],
    "hummer": ["h1", "h2", "h3"],
    "hyundai": [
        "accent",
        "aero",
        "aero express",
        "aero queen",
        "aero space",
        "aero town",
        "atos",
        "avante",
        "azera",
        "bayon",
        "casper",
        "celesta",
        "centennial",
        "click",
        "county",
        "coupe",
        "creta",
        "custo",
        "dynasty",
        "elantra",
        "encino",
        "eon",
        "equus",
        "excel",
        "galloper",
        "genesis",
        "getz",
        "grace",
        "grand santa fe",
        "grand starex",
        "grandeur",
        "h1",
        "h100",
        "h200",
        "h350",
        "hd120",
        "hd170",
        "hd35",
        "hd450",
        "hd500",
        "hd65",
        "hd72",
        "hd78",
        "i10",
        "i20",
        "i20 active",
        "i30",
        "i40",
        "i800",
        "ioniq",
        "ioniq 5",
        "ioniq 6",
        "ix20",
        "ix25",
        "ix35",
        "ix55",
        "kona",
        "kona electric",
        "lafesta",
        "lantra",
        "lavita",
        "libero",
        "marcia",
        "matrix",
        "maxcruze",
        "mighty",
        "mufasa",
        "nexo",
        "nf",
        "palisade",
        "pony",
        "porter",
        "presto",
        "s coupe",
        "santa cruz",
        "santa fe",
        "santa fe classic",
        "santamo",
        "scoupe",
        "solaris",
        "sonata",
        "starex",
        "staria",
        "stellar",
        "tager",
        "terracan",
        "tiburon",
        "trajet",
        "tucson",
        "tuscani",
        "veloster",
        "venue",
        "veracruz",
        "verna",
        "xg",
        "богдан",
    ],
    "infiniti": [
        "ex25",
        "ex30d",
        "ex35",
        "ex37",
        "fx30d",
        "fx35",
        "fx37",
        "fx45",
        "fx50",
        "g20",
        "g25",
        "g35",
        "g37",
        "i30",
        "i35",
        "j30",
        "jx35",
        "m25",
        "m35",
        "m35 hybrid",
        "m37",
        "m45",
        "m56",
        "q30",
        "q40",
        "q45",
        "q50",
        "q60",
        "q70",
        "qx30",
        "qx4",
        "qx50",
        "qx55",
        "qx56",
        "qx60",
        "qx70",
        "qx80",
    ],
    "iran khodro": ["dena", "runna", "samand", "sarir", "soren", "tara"],
    "isuzu": [
        "117 coupe",
        "amigo",
        "ascender",
        "aska",
        "axiom",
        "bighorn",
        "citibus",
        "como",
        "d-max",
        "elf",
        "fargo",
        "fargo filly",
        "faster",
        "filly",
        "forward",
        "gemini",
        "giga",
        "i-mark",
        "impulse",
        "lingtuo",
        "midi",
        "mu",
        "mu-x",
        "pa nero",
        "piazza",
        "piazza nero",
        "rodeo",
        "stylus",
        "t17",
        "tf",
        "tractor",
        "trooper",
        "vehicross",
        "wizard",
    ],
    "jac": [
        "hfc 1040k",
        "hfc 1045k",
        "hfc 1061k",
        "iev5",
        "iev6e",
        "iev6e sport",
        "iev6s",
        "iev7l",
        "iev7s",
        "ieva50",
        "ievs4",
        "j2",
        "j3",
        "j4",
        "j5",
        "j6",
        "j7",
        "jiayue a5",
        "js3",
        "js4",
        "js6",
        "m1",
        "n120",
        "n35",
        "n56",
        "n75",
        "n80",
        "refine",
        "refine a60",
        "refine l6 max",
        "refine m3",
        "refine m5",
        "refine m6",
        "refine r3",
        "refine s2",
        "refine s3",
        "refine s4",
        "refine s5",
        "refine s7",
        "rein",
        "s1",
        "s3",
        "s5",
        "s7",
        "sehol a5",
        "sehol a5 plus",
        "sehol aipao",
        "sehol e10x",
        "sehol e40x",
        "sehol qx",
        "sehol x4",
        "sehol x6",
        "sehol x8",
        "sehol x8 plus",
        "sunray",
        "t40",
        "t6",
        "t8",
        "t8 pro",
        "yttrium 3",
    ],
    "jaguar": [
        "daimler",
        "e-pace",
        "f-pace",
        "f-type",
        "i-pace",
        "s-type",
        "sovereign",
        "x-type",
        "xe",
        "xf",
        "xj",
        "xj220",
        "xjs",
        "xk",
    ],
    "jeep": [
        "avenger",
        "cherokee",
        "commander",
        "compass",
        "gladiator",
        "grand cherokee",
        "grand commander",
        "grand wagoneer",
        "liberty",
        "patriot",
        "renegade",
        "wagoneer",
        "wrangler",
    ],
    "kia": [
        "avella",
        "besta",
        "bongo",
        "borrego",
        "cadenza",
        "capital",
        "carens",
        "carnival",
        "carstar",
        "ceed",
        "cerato",
        "cerato koup",
        "ceres",
        "clarus",
        "comby",
        "credos",
        "elan",
        "enterprise",
        "ev5",
        "ev6",
        "ev9",
        "forte",
        "grand carnival",
        "joice",
        "k серия",
        "k2",
        "k3",
        "k4",
        "k5",
        "k7",
        "k8",
        "k9",
        "k900",
        "kx cross",
        "kx1",
        "kx3",
        "kx5",
        "kx7",
        "lotze",
        "magentis",
        "mohave",
        "morning",
        "niro",
        "opirus",
        "optima",
        "optima regal",
        "pegas",
        "picanto",
        "potentia",
        "pregio",
        "pride",
        "proceed",
        "qianlima",
        "quoris",
        "ray",
        "regal",
        "retona",
        "rio",
        "rio x (x-line)",
        "rondo",
        "sedona",
        "seltos",
        "sephia",
        "shuma",
        "sonet",
        "sorento",
        "soul",
        "spectra",
        "sportage",
        "stinger",
        "stonic",
        "telluride",
        "towner",
        "venga",
        "visto",
        "x-trek",
        "xceed",
    ],
    "koenigsegg": ["agera", "cc8s", "ccr", "ccx", "ccxr", "trevita"],
    "lamborghini": [
        "350 gt",
        "400 gt",
        "aventador",
        "countach",
        "diablo",
        "espada",
        "gallardo",
        "huracan",
        "islero",
        "jarama",
        "lm 002",
        "miura",
        "murcielago",
        "reventon",
        "revuelto",
        "sian",
        "urus",
    ],
    "lancia": [
        "dedra",
        "delta",
        "kappa",
        "lybra",
        "montecarlo",
        "musa",
        "phedra",
        "prisma",
        "thema",
        "thesis",
        "y",
        "ypsilon",
        "zeta",
    ],
    "land rover": [
        "defender",
        "discovery",
        "discovery sport",
        "freelander",
        "range rover",
        "range rover evoque",
        "range rover sport",
        "range rover velar",
        "series iii",
    ],
    "lexus": [
        "ct200h",
        "es200",
        "es250",
        "es300",
        "es300h",
        "es330",
        "es350",
        "gs f",
        "gs200t",
        "gs250",
        "gs300",
        "gs300h",
        "gs350",
        "gs400",
        "gs430",
        "gs450h",
        "gs460",
        "gx460",
        "gx470",
        "gx550",
        "hs250h",
        "is f",
        "is200",
        "is200d",
        "is200t",
        "is220d",
        "is250",
        "is250c",
        "is300",
        "is300c",
        "is300h",
        "is350",
        "is350c",
        "is500",
        "lbx",
        "lc500",
        "lc500h",
        "lfa",
        "lm300h",
        "lm350",
        "lm350h",
        "lm500h",
        "ls350",
        "ls400",
        "ls430",
        "ls460",
        "ls460l",
        "ls500",
        "ls500h",
        "ls600h",
        "ls600hl",
        "lv500h",
        "lx450",
        "lx450d",
        "lx470",
        "lx500d",
        "lx570",
        "lx600",
        "nx200",
        "nx200t",
        "nx250",
        "nx300",
        "nx300h",
        "nx350",
        "nx350h",
        "nx450h+",
        "rc f",
        "rc200t",
        "rc300",
        "rc300h",
        "rc350",
        "rx200t",
        "rx270",
        "rx300",
        "rx330",
        "rx350",
        "rx350h",
        "rx350l",
        "rx400h",
        "rx450h",
        "rx450h+",
        "rx450hl",
        "rx500h",
        "rz450e",
        "sc300",
        "sc400",
        "sc430",
        "tx350",
        "tx500h",
        "tx550h+",
        "ux200",
        "ux250h",
        "ux300e",
    ],
    "lifan": [
        "650 ev",
        "breez",
        "cebrium",
        "celliya",
        "foison",
        "murman",
        "myway",
        "smily",
        "solano",
        "x50",
        "x60",
        "x70",
        "x80",
    ],
    "lincoln": [
        "aviator",
        "blackwood",
        "continental",
        "corsair",
        "ls",
        "mark lt",
        "mark viii",
        "mkc",
        "mks",
        "mkt",
        "mkx",
        "mkz",
        "nautilus",
        "navigator",
        "town car",
        "zephyr",
    ],
    "lotus": [
        "2-eleven",
        "3-eleven",
        "eletre",
        "elise",
        "emeya",
        "esprit",
        "europa s",
        "evora",
        "exige",
        "super 7",
    ],
    "luxgen": ["5 sedan", "7 mpv", "7 suv"],
    "marussia": ["b1", "b2"],
    "maserati": [
        "3200 gt",
        "coupe",
        "ghibli",
        "grancabrio",
        "gransport",
        "granturismo",
        "grecale",
        "levante",
        "mc12",
        "mc20",
        "quattroporte",
        "spyder",
    ],
    "maybach": ["57", "62"],
    "mazda": [
        "121",
        "1500",
        "323",
        "323c",
        "323f",
        "616",
        "626",
        "818",
        "929",
        "atenza",
        "autozam az-1",
        "autozam az-3",
        "autozam clef",
        "autozam revue",
        "axela",
        "az-offroad",
        "az-wagon",
        "b серия",
        "biante",
        "bongo",
        "bongo brawny",
        "bongo brawny truck",
        "bongo friendee",
        "bongo truck",
        "bt-50",
        "capella",
        "carol",
        "chantez",
        "cosmo",
        "cronos",
        "cx-3",
        "cx-30",
        "cx-4",
        "cx-5",
        "cx-50",
        "cx-60",
        "cx-7",
        "cx-8",
        "cx-9",
        "cx-90",
        "demio",
        "efini mpv",
        "efini ms-6",
        "efini ms-8",
        "efini ms-9",
        "efini rx-7",
        "etude",
        "eunos 100",
        "eunos 300",
        "eunos 500",
        "eunos 800",
        "eunos cargo",
        "eunos cosmo",
        "eunos presso",
        "eunos roadster",
        "familia",
        "familia s-wagon",
        "flair",
        "flair crossover",
        "flair wagon",
        "lantis",
        "laputa",
        "luce",
        "mazda2",
        "mazda3",
        "mazda3 mps",
        "mazda5",
        "mazda6",
        "mazda6 mps",
        "mazda8",
        "miata",
        "millenia",
        "mpv",
        "mx-3",
        "mx-30",
        "mx-5",
        "mx-6",
        "navajo",
        "persona",
        "premacy",
        "proceed",
        "proceed levante",
        "proceed marvie",
        "protege",
        "protege5",
        "revue",
        "roadster",
        "rx-5",
        "rx-7",
        "rx-8",
        "savanna rx-7",
        "scrum",
        "sentia",
        "spiano",
        "titan",
        "tribute",
        "truck",
        "verisa",
        "xedos 6",
        "xedos 9",
    ],
    "mclaren": ["12c", "520s", "540c", "570gt", "650s", "720s", "f1", "p1"],
    "mercedes-benz": [
        "190",
        "a-class",
        "actros 4x2",
        "actros 6x2",
        "actros 6x4",
        "amg gt",
        "arocs 4x2",
        "arocs 4x4",
        "arocs 6x2",
        "arocs 6x4",
        "arocs 6x6",
        "arocs 8x2",
        "arocs 8x4",
        "arocs 8x6",
        "arocs 8x8",
        "atego",
        "axor",
        "b-class",
        "c-class",
        "citan",
        "cl-class",
        "cla-class",
        "clc-class",
        "cle-class",
        "clk-class",
        "cls-class",
        "e-class",
        "eqa",
        "eqb",
        "eqc",
        "eqe",
        "eqe suv",
        "eqs",
        "eqs suv",
        "eqv",
        "g-class",
        "gl-class",
        "gla-class",
        "glb-class",
        "glc",
        "glc coupe",
        "gle",
        "gle coupe",
        "glk-class",
        "gls-class",
        "lk",
        "m-class",
        "mb100",
        "mercedes",
        "metris",
        "o 303",
        "o 405",
        "r-class",
        "s-class",
        "sk",
        "sl-class",
        "slc-class",
        "slk-class",
        "slr mclaren",
        "sls amg",
        "sprinter",
        "sprinter classic",
        "t1",
        "t2",
        "tourismo",
        "unimog",
        "v-class",
        "vaneo",
        "vario",
        "viano",
        "vito",
        "w111",
        "w114",
        "w115",
        "w123",
        "w128",
        "w136",
        "w143",
        "w180",
        "w187",
        "w189",
        "x-class",
    ],
    "mercury": [
        "cougar",
        "grand marquis",
        "marauder",
        "mariner",
        "marquis",
        "milan",
        "montego",
        "monterey",
        "mountaineer",
        "mystique",
        "sable",
        "topaz",
        "tracer",
        "villager",
        "zephyr",
    ],
    "mini": [
        "cabrio",
        "classic",
        "clubman",
        "countryman",
        "coupe",
        "crossover",
        "hatch",
        "paceman",
        "roadster",
    ],
    "mitsubishi": [
        "3000gt",
        "airtrek",
        "aspire",
        "asx",
        "attrage",
        "bravo",
        "carisma",
        "celeste",
        "challenger",
        "chariot",
        "chariot grandis",
        "colt",
        "colt plus",
        "cordia",
        "debonair",
        "delica",
        "delica cargo",
        "delica d:2",
        "delica d:3",
        "delica d:5",
        "delica mini",
        "delica van",
        "diamante",
        "dignity",
        "dion",
        "eclipse",
        "eclipse cross",
        "ek active",
        "ek classy",
        "ek custom",
        "ek space",
        "ek sport",
        "ek wagon",
        "ek x ev",
        "emeraude",
        "endeavor",
        "eterna",
        "expo",
        "freeca",
        "fto",
        "fuso",
        "fuso canter",
        "galant",
        "galant fortis",
        "grandis",
        "grunder",
        "gto",
        "i",
        "i-miev",
        "jeep",
        "l200",
        "l300",
        "l300 truck",
        "l400",
        "lancer",
        "lancer cedia",
        "lancer evolution",
        "lancer ex",
        "lancer fortis",
        "legnum",
        "libero",
        "magna wagon",
        "mighty max",
        "minica",
        "minica toppo",
        "minicab",
        "minicab miev",
        "mirage",
        "mirage dingo",
        "montero",
        "montero sport",
        "nativa",
        "nimbus",
        "outlander",
        "outlander sport",
        "pajero",
        "pajero io",
        "pajero junior",
        "pajero mini",
        "pajero pinin",
        "pajero sport",
        "pistachio",
        "proudia",
        "raider",
        "rosa",
        "rvr",
        "sapporo",
        "savrin",
        "sigma",
        "space gear",
        "space runner",
        "space star",
        "space wagon",
        "starion",
        "strada",
        "toppo",
        "toppo bj",
        "toppo bj wide",
        "town box",
        "town box wide",
        "towny",
        "tredia",
        "triton",
        "xpander",
        "xpander cross",
    ],
    "mitsuoka": [
        "buddy",
        "classic type-f",
        "galue",
        "galue classic",
        "galue convertible",
        "galue limousine s50",
        "galue-i",
        "galue-ii",
        "galue204",
        "himiko",
        "le-seyde",
        "like",
        "mc-1",
        "micro car",
        "nouera",
        "orochi",
        "ray",
        "rock star",
        "ryoga",
        "ryugi",
        "td 2000",
        "viewt",
        "yuga",
        "zero 1",
    ],
    "nissan": [
        "100nx",
        "180sx",
        "200sx",
        "240sx",
        "300zx",
        "350z",
        "370z",
        "ad",
        "almera",
        "almera classic",
        "altima",
        "ariya",
        "armada",
        "atlas",
        "aura",
        "auster",
        "avenir",
        "avenir salut",
        "bassara",
        "be-1",
        "bluebird",
        "bluebird maxima",
        "bluebird sylphy",
        "cabstar",
        "caravan",
        "caravan elgrand",
        "cedric",
        "cedric cima",
        "cefiro",
        "cherry",
        "cima",
        "civilian",
        "clipper",
        "condor",
        "crew",
        "cube",
        "cube cubic",
        "datsun",
        "dayz",
        "dayz roox",
        "diesel",
        "dualis",
        "e-nv200",
        "elgrand",
        "exa",
        "expert",
        "fairlady z",
        "figaro",
        "frontier",
        "fuga",
        "gloria",
        "gloria cima",
        "grand livina",
        "gt-r",
        "homy",
        "homy elgrand",
        "hypermini",
        "interstar",
        "juke",
        "kicks",
        "king cab",
        "kix",
        "kubistar",
        "lafesta",
        "langley",
        "lannia",
        "largo",
        "latio",
        "laurel",
        "laurel spirit",
        "leaf",
        "leopard",
        "liberta villa",
        "liberty",
        "livina",
        "lucino",
        "march",
        "march box",
        "maxima",
        "micra",
        "micra c+c",
        "mistral",
        "moco",
        "murano",
        "navara",
        "note",
        "np300",
        "nt100 clipper",
        "nv",
        "nv100 clipper",
        "nv200",
        "nv300",
        "nv350 caravan",
        "nv400",
        "nx-coupe",
        "otti",
        "pao",
        "pathfinder",
        "patrol",
        "pickup",
        "pino",
        "pixo",
        "prairie",
        "prairie joy",
        "presage",
        "presea",
        "president",
        "primastar",
        "primera",
        "primera camino",
        "pulsar",
        "qashqai",
        "qashqai+2",
        "quest",
        "r'nessa",
        "rasheen",
        "rogue",
        "rogue sport",
        "roox",
        "s-cargo",
        "safari",
        "sakura",
        "sentra",
        "serena",
        "silvia",
        "skyline",
        "skyline crossover",
        "skyline gt-r",
        "stagea",
        "stanza",
        "sunny",
        "sunny california",
        "sunny rz-1",
        "sylphy",
        "teana",
        "terra",
        "terrano",
        "terrano ii",
        "terrano regulus",
        "tiida",
        "tiida latio",
        "tino",
        "titan",
        "trade",
        "urvan",
        "vanette",
        "vanette serena",
        "vanette truck",
        "versa",
        "violet",
        "volkswagen santana",
        "wingroad",
        "x-trail",
        "xterra",
        "z",
    ],
    "oldsmobile": [
        "88",
        "achieva",
        "alero",
        "aurora",
        "bravada",
        "cutlass ciera",
        "cutlass supreme",
        "omega",
        "silhouette",
    ],
    "opel": [
        "1200",
        "1900",
        "adam",
        "admiral",
        "agila",
        "ampera",
        "antara",
        "arena",
        "ascona",
        "astra",
        "astra family",
        "astra gtc",
        "calibra",
        "campo",
        "cascada",
        "combo",
        "commodore",
        "corsa",
        "crossland",
        "diplomat",
        "frontera",
        "grandland x",
        "gt",
        "insignia",
        "kadett",
        "kapitan",
        "karl",
        "manta",
        "meriva",
        "mokka",
        "monterey",
        "monza",
        "movano",
        "olympia",
        "omega",
        "rekord",
        "rocks-e",
        "senator",
        "signum",
        "sintra",
        "speedster",
        "tigra",
        "vectra",
        "vita",
        "vivaro",
        "zafira",
        "zafira life",
    ],
    "pagani": ["huayra", "zonda"],
    "peugeot": [
        "1007",
        "104",
        "106",
        "107",
        "108",
        "2008",
        "201",
        "202",
        "203",
        "204",
        "205",
        "206",
        "207",
        "207i",
        "208",
        "3008",
        "301",
        "304",
        "305",
        "306",
        "307",
        "308",
        "309",
        "4007",
        "4008",
        "403",
        "404",
        "405",
        "406",
        "407",
        "408",
        "5008",
        "504",
        "505",
        "508",
        "604",
        "605",
        "607",
        "806",
        "807",
        "bipper",
        "boxer",
        "expert",
        "ion",
        "j5",
        "j9",
        "partner",
        "partner origin",
        "partner tepee",
        "rcz",
        "rifter",
        "traveller",
    ],
    "plymouth": [
        "acclaim",
        "breeze",
        "grand voyager",
        "horizon",
        "laser",
        "neon",
        "prowler",
        "reliant",
        "voyager",
    ],
    "pontiac": [
        "6000",
        "aztek",
        "bonneville",
        "fiero",
        "firebird",
        "g6",
        "grand am",
        "grand prix",
        "gto",
        "lemans",
        "montana",
        "solstice",
        "sunbird",
        "sunfire",
        "torrent",
        "trans am",
        "trans sport",
        "vibe",
        "wave",
    ],
    "porsche": [
        "356",
        "911",
        "918",
        "924",
        "928",
        "944",
        "968",
        "boxster",
        "carrera gt",
        "cayenne",
        "cayenne coupe",
        "cayman",
        "macan",
        "panamera",
        "taycan",
    ],
    "proton": [
        "arena",
        "gen2",
        "iswara",
        "perdana",
        "persona",
        "putra",
        "saga",
        "satria neo",
        "savvy",
        "tiara",
        "waja",
        "wira",
    ],
    "ravon": ["gentra", "matiz", "nexia r3", "r2", "r4"],
    "renault": [
        "11",
        "14",
        "19",
        "21",
        "25",
        "arkana",
        "austral",
        "avantime",
        "captur",
        "city k-ze",
        "clio",
        "dokker",
        "dokker stepway",
        "duster",
        "espace",
        "estafette",
        "express",
        "fluence",
        "fluence z.e.",
        "grand scenic",
        "kadjar",
        "kangoo",
        "kangoo z.e.",
        "kaptur",
        "kerax",
        "koleos",
        "kwid",
        "laguna",
        "latitude",
        "lodgy",
        "logan",
        "logan stepway",
        "lutecia",
        "magnum",
        "major",
        "mascott",
        "master",
        "maxity",
        "megane",
        "midliner",
        "midlum",
        "modus",
        "premium",
        "r19",
        "r5",
        "r9",
        "rapid",
        "safrane",
        "sandero",
        "sandero stepway",
        "scenic",
        "scenic rx4",
        "sport spider",
        "symbol",
        "t серия",
        "talisman",
        "trafic",
        "twingo",
        "twizy",
        "vel satis",
        "wind",
        "zoe",
    ],
    "renault samsung": [
        "qm3",
        "qm5",
        "qm6",
        "sm3",
        "sm3 z.e.",
        "sm5",
        "sm6",
        "sm7",
        "xm3",
    ],
    "rolls-royce": [
        "20/25",
        "corniche",
        "cullinan",
        "dawn",
        "flying spur",
        "ghost",
        "park ward",
        "phantom",
        "phantom drophead",
        "rolls-royce",
        "silver cloud",
        "silver seraph",
        "silver spirit",
        "silver spur",
        "wraith",
    ],
    "rover": [
        "14",
        "200",
        "25",
        "400",
        "45",
        "600",
        "75",
        "800",
        "rover",
        "streetwise",
    ],
    "saab": [
        "9-2x",
        "9-3",
        "9-4x",
        "9-5",
        "9-7x",
        "90",
        "900",
        "9000",
        "92",
        "93",
        "95",
        "96",
        "99",
        "saab",
        "sonett",
    ],
    "saturn": [
        "astra",
        "aura",
        "ion",
        "l серия",
        "l200",
        "outlook",
        "relay",
        "s серия",
        "saturn",
        "sky",
        "sl1",
        "sl2",
        "vue",
    ],
    "scion": ["fr-s", "ia", "im", "iq", "tc", "xa", "xb", "xd"],
    "seat": [
        "131",
        "133",
        "alhambra",
        "altea",
        "arona",
        "arosa",
        "ateca",
        "cordoba",
        "exeo",
        "ibiza",
        "inca",
        "leon",
        "marbella",
        "mii",
        "ronda",
        "seat",
        "tarraco",
        "terra",
        "toledo",
    ],
    "skoda": [
        "100",
        "1000/1100 mb",
        "105/120/125",
        "1101/1102",
        "1201",
        "1202",
        "1203",
        "440/445/450",
        "citigo",
        "enyaq iv",
        "enyaq iv coupe",
        "fabia",
        "favorit",
        "felicia",
        "forman",
        "garde",
        "kamiq",
        "karoq",
        "kodiaq",
        "octavia",
        "popular",
        "praktik",
        "rapid",
        "roomster",
        "scala",
        "superb",
        "yeti",
    ],
    "smart": ["#1", "#3", "city", "crossblade", "forfour", "fortwo", "roadster"],
    "ssangyong": [
        "actyon",
        "actyon sports",
        "chairman",
        "istana",
        "kallista",
        "korando",
        "korando family",
        "korando sports",
        "korando turismo",
        "kyron",
        "musso",
        "musso sports",
        "nomad",
        "rexton",
        "rexton sports",
        "rexton sports khan",
        "rodius",
        "ssangyong",
        "stavic",
        "tivoli",
        "tivoli xlv",
        "torres",
        "torres evx",
    ],
    "subaru": [
        "1300",
        "1600",
        "1800",
        "alcyone",
        "ascent",
        "b9 tribeca",
        "baja",
        "bistro",
        "brat",
        "brz",
        "chiffon",
        "crosstrek",
        "dex",
        "dias wagon",
        "domingo",
        "exiga",
        "exiga crossover 7",
        "forester",
        "impreza",
        "impreza wrx",
        "impreza wrx sti",
        "impreza xv",
        "justy",
        "layback",
        "legacy",
        "legacy b4",
        "legacy lancaster",
        "leone",
        "levorg",
        "libero",
        "lucra",
        "outback",
        "pleo",
        "pleo nesta",
        "pleo plus",
        "r1",
        "r2",
        "rex",
        "sambar",
        "sambar truck",
        "solterra",
        "stella",
        "svx",
        "traviq",
        "trezia",
        "tribeca",
        "vivio",
        "wrx sti",
        "xt",
        "xv",
    ],
    "suzuki": [
        "across",
        "aerio",
        "alto",
        "alto lapin",
        "baleno",
        "cappuccino",
        "cara",
        "carry truck",
        "carry van",
        "celerio",
        "cervo",
        "ciaz",
        "cultus",
        "cultus crescent",
        "eeco",
        "equator",
        "ertiga",
        "escudo",
        "esteem",
        "every",
        "forenza",
        "fronte",
        "grand escudo",
        "grand vitara",
        "grand vitara xl-7",
        "hustler",
        "ignis",
        "jimny",
        "jimny sierra",
        "jimny wide",
        "join",
        "joy pop",
        "kei",
        "kizashi",
        "landy",
        "lapin",
        "liana",
        "mighty boy",
        "mr wagon",
        "palette",
        "reno",
        "s-presso",
        "samurai",
        "sidekick",
        "solio",
        "spacia",
        "splash",
        "swift",
        "swift+",
        "sx4",
        "twin",
        "verona",
        "vitara",
        "wagon r",
        "wagon r plus",
        "wagon r smile",
        "wagon r solio",
        "wagon r wide",
        "works",
        "x-90",
        "xbee",
        "xl7",
    ],
    "tesla": [
        "cybertruck",
        "model 3",
        "model s",
        "model x",
        "model y",
        "roadster",
        "semi",
    ],
    "tianye": ["admiral", "tianye"],
    "toyota": [
        "2000gt",
        "4runner",
        "allex",
        "allion",
        "alphard",
        "altezza",
        "aqua",
        "aristo",
        "aurion",
        "auris",
        "avalon",
        "avanza",
        "avensis",
        "avensis verso",
        "aygo",
        "bb",
        "belta",
        "blade",
        "blizzard",
        "brevis",
        "bz3",
        "bz4x",
        "c+pod",
        "c-hr",
        "caldina",
        "cami",
        "camry",
        "camry gracia",
        "camry prominent",
        "carina",
        "carina e",
        "carina ed",
        "carina ii",
        "cavalier",
        "celica",
        "celsior",
        "century",
        "chaser",
        "classic",
        "coaster",
        "comfort",
        "coms",
        "corolla",
        "corolla altis",
        "corolla axio",
        "corolla ceres",
        "corolla cross",
        "corolla fielder",
        "corolla fx",
        "corolla ii",
        "corolla im",
        "corolla levin",
        "corolla rumion",
        "corolla runx",
        "corolla spacio",
        "corolla verso",
        "corona",
        "corona exiv",
        "corona premio",
        "corona sf",
        "corsa",
        "cressida",
        "cresta",
        "crown",
        "crown kluger",
        "crown majesta",
        "crown signia",
        "curren",
        "cynos",
        "deliboy",
        "duet",
        "dyna",
        "echo",
        "esquire",
        "estima",
        "estima emina",
        "estima lucida",
        "etios",
        "etios cross",
        "fj cruiser",
        "fortuner",
        "frontlander",
        "funcargo",
        "gaia",
        "gr 86",
        "granace",
        "grand hiace",
        "grand highlander",
        "granvia",
        "gt 86",
        "harrier",
        "hiace",
        "hiace regius",
        "hiace truck",
        "highlander",
        "hilux",
        "hilux surf",
        "innova",
        "ipsum",
        "iq",
        "isis",
        "ist",
        "izoa",
        "jpn taxi",
        "kluger v",
        "land cruiser",
        "land cruiser cygnus",
        "land cruiser prado",
        "lite ace",
        "lite ace noah",
        "lite ace truck",
        "mark ii",
        "mark ii wagon blit",
        "mark ii wagon qualis",
        "mark x",
        "mark x zio",
        "master ace surf",
        "matrix",
        "mega cruiser",
        "mirai",
        "model f",
        "mr-s",
        "mr2",
        "nadia",
        "noah",
        "opa",
        "origin",
        "paseo",
        "passo",
        "passo sette",
        "picnic",
        "pixis epoch",
        "pixis joy",
        "pixis mega",
        "pixis space",
        "pixis truck",
        "pixis van",
        "platz",
        "porte",
        "premio",
        "previa",
        "prius",
        "prius alpha",
        "prius c",
        "prius phv",
        "prius plus",
        "prius prime",
        "prius v",
        "proace",
        "probox",
        "progres",
        "pronard",
        "publica",
        "ractis",
        "raize",
        "raum",
        "rav4",
        "regius",
        "regius ace",
        "roomy",
        "rush",
        "sai",
        "scepter",
        "sd",
        "sequoia",
        "sera",
        "sf",
        "sienna",
        "sienta",
        "soarer",
        "solara",
        "soluna",
        "spade",
        "sparky",
        "sprinter",
        "sprinter carib",
        "sprinter marino",
        "sprinter trueno",
        "starlet",
        "succeed",
        "supra",
        "t100",
        "tacoma",
        "tank",
        "tercel",
        "touring hiace",
        "town ace",
        "town ace noah",
        "town ace truck",
        "toyoace",
        "tundra",
        "urban cruiser",
        "vanguard",
        "vellfire",
        "veloz",
        "venza",
        "verossa",
        "verso",
        "verso-s",
        "vios",
        "vista",
        "vista ardeo",
        "vitz",
        "voltz",
        "voxy",
        "wigo",
        "wildlander",
        "will cypha",
        "will vi",
        "will vs",
        "windom",
        "wish",
        "yaris",
        "yaris ativ",
        "yaris cross",
        "yaris ia",
        "yaris verso",
    ],
    "volkswagen": [
        "amarok",
        "arteon",
        "atlas",
        "beetle",
        "bora",
        "caddy",
        "california",
        "caravelle",
        "corrado",
        "country",
        "crafter",
        "derby",
        "eos",
        "fox",
        "golf",
        "golf plus",
        "id.3",
        "id.4",
        "id.4 crozz",
        "id.4 x",
        "id.5",
        "id.6 crozz",
        "id.6 x",
        "id.7",
        "id.buzz",
        "jetta",
        "kaefer",
        "lavida",
        "lavida xr",
        "lt",
        "lupo",
        "magotan",
        "multivan",
        "parati",
        "passat",
        "passat cc",
        "phaeton",
        "pointer",
        "polo",
        "quantum",
        "rabbit",
        "routan",
        "santana",
        "saveiro",
        "scirocco",
        "sharan",
        "t-cross",
        "t-roc",
        "tacqua",
        "talagon",
        "taos",
        "taro",
        "tavendor",
        "tayron",
        "tayron x",
        "teramont",
        "teramont x",
        "tharu",
        "tiguan",
        "tiguan allspace",
        "tiguan x",
        "touareg",
        "touran",
        "transporter",
        "type 2",
        "up!",
        "vento",
        "viloran",
        "xl1",
    ],
    "volvo": [
        "240",
        "340",
        "343",
        "345",
        "360",
        "440",
        "460",
        "480",
        "740",
        "760",
        "850",
        "940",
        "960",
        "c30",
        "c40",
        "c70",
        "em90",
        "ex90",
        "fe",
        "fh",
        "fl",
        "fm",
        "fmx",
        "laplander",
        "s40",
        "s60",
        "s70",
        "s80",
        "s90",
        "t5",
        "v40",
        "v50",
        "v60",
        "v70",
        "v90",
        "vnl series",
        "volvo",
        "xc40",
        "xc60",
        "xc70",
        "xc90",
    ],
    "vortex": ["corda", "estina", "tingo"],
    "zotye": ["coupa", "nomade", "t600", "t600 coupe", "z100", "z300"],
    "zx": ["admiral", "chanling", "grandtiger", "landmark", "weishi 1949"],
    "газ": [
        "12 зим",
        "13 чайка",
        "14 чайка",
        "18",
        "21 волга",
        "22 волга",
        "2217",
        "2330 тигр",
        "24 волга",
        "2784",
        "3102 волга",
        "31029 волга",
        "3105 волга",
        "3110 волга",
        "31105 волга",
        "3111 волга",
        "3306",
        "3307",
        "3308",
        "3309",
        "3325",
        "4301",
        "51",
        "52",
        "53",
        "63",
        "66",
        "67",
        "69",
        "валдай",
        "валдай 8",
        "валдай некст",
        "волга сайбер",
        "газель",
        "газель некст",
        "газель нн",
        "газель сити",
        "газон некст",
        "м-72",
        "м1",
        "победа",
        "садко некст",
        "саз 3507",
        "саз 3512",
        "соболь",
        "соболь нн",
        "трофим",
        "чайка",
    ],
    "заз": [
        "вида",
        "дана",
        "заз",
        "запорожец",
        "ланос",
        "пикап",
        "сенс",
        "славута",
        "таврия",
        "форца",
        "шанс",
    ],
    "иж": ["2125 комби", "2126 ода", "21261 фабула", "2715", "2717"],
    "ваз": [
        "1111 ока",
        "2101",
        "2102",
        "2103",
        "2104",
        "2105",
        "2106",
        "2107",
        "2108",
        "2109",
        "21099",
        "2110",
        "2111",
        "2112",
        "2113 самара",
        "2114 самара",
        "2115 самара",
        "2120 надежда",
        "2129",
        "4x4 2121 нива",
        "4x4 2131 нива",
        "4x4 бронто",
        "4x4 урбан",
        "el lada",
        "веста",
        "веста кросс",
        "веста спорт",
        "гранта",
        "гранта кросс",
        "гранта спорт",
        "калина",
        "калина кросс",
        "калина спорт",
        "ларгус",
        "ларгус кросс",
        "нива (2020-21 гг.)",
        "нива бронто",
        "нива легенд",
        "нива пикап",
        "нива тревел",
        "приора",
        "х-кросс 5",
        "х-рей",
        "х-рей кросс",
    ],
    "луаз": ["1302", "969"],
    "москвич": [
        "2136",
        "2137",
        "2138",
        "2140",
        "2141",
        "2142",
        "2335",
        "2734",
        "2901",
        "3",
        "3е",
        "400",
        "401",
        "402",
        "403",
        "407",
        "408",
        "410",
        "411",
        "412",
        "423",
        "424",
        "426",
        "427",
        "434",
        "6",
    ],
    "тагаз": [
        "aquila",
        "вега",
        "мастер",
        "роад партнер",
        "с10",
        "с190",
        "с30",
        "тагер",
        "тинго",
        "харди",
        "эстина",
    ],
    "уаз": [
        "2360",
        "3151",
        "3153",
        "3159",
        "3160",
        "469",
        "буханка",
        "карго",
        "патриот",
        "патриот спорт",
        "пикап",
        "профи",
        "симбир",
        "хантер",
    ],
}
